In [1]:
import cv2
import os
import pandas as pd
import ast

d:\anaconda3\envs\tf2.4\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\anaconda3\envs\tf2.4\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
d:\anaconda3\envs\tf2.4\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
compiled_lab_1 = pd.read_csv("../../csv/LAB_HOCS/LAB_HOCS_1.csv", index_col=None)
compiled_lab_2 = pd.read_csv("../../csv/LAB_HOCS/LAB_HOCS_2.csv", index_col=None)
compiled_lab_3 = pd.read_csv("../../csv/LAB_HOCS/LAB_HOCS_3.csv", index_col=None)
lab = pd.concat([compiled_lab_1, compiled_lab_2, compiled_lab_3])
lab = lab.reset_index(drop=True)
lab

,contours,area_hist_values,int_hist_values,plant
0,[[[[144 110]]\n\n [[143 111]]\n\n [[142 111]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 20. 22. 51. 41. 46. 35. 29. 25. 21. ...,acer_campestre
1,[[[[158 107]]\n\n [[157 108]]\n\n [[156 108]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 21. 31. 59. 52. 40. 41. 24. 21. 11. ...,acer_campestre
2,[[[[142 86]]\n\n [[141 87]]\n\n [[140 87]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 7. 23. 54. 34. 49. 33. 30. 24. 20. ...,acer_campestre
3,[[[[162 85]]\n\n [[161 86]]\n\n [[160 86]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 22. 34. 54. 48. 46. 40. 24. 8. 4. ...,acer_campestre
4,[[[[185 100]]\n\n [[184 101]]\n\n [[183 101]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 3. 15. 27. 45. 40. 40. 34. 18. 26. ...,acer_campestre
...,...,...,...,...
14569,[[[[109 52]]\n\n [[108 53]]\n\n [[107 53]...,[ 0. 0. 0. 0. 0. 0. 1. 8. 25. ...,[ 23. 77. 86. 75. 69. 76. 35. 33. 21. ...,quercus_robur
14570,[[[[115 78]]\n\n [[114 79]]\n\n [[113 79]...,[ 0. 0. 0. 0. 0. 0. 0. 1. 11. ...,[ 28. 68. 48. 69. 68. 54. 14. 3. 3. ...,quercus_robur
14571,[[[[ 94 101]]\n\n [[ 93 102]]\n\n [[ 92 103]...,[ 0. 0. 0. 0. 0. 0. 0. 1. 16. ...,[ 22. 53. 69. 75. 50. 42. 17. 11. 2. ...,quercus_robur
14572,[[[[116 79]]\n\n [[115 80]]\n\n [[114 81]...,[ 0. 0. 0. 0. 0. 0. 0. 2. 23. ...,[ 34. 84. 62. 59. 58. 51. 15. 5. 0. ...,quercus_robur
14573,[[[[ 99 66]]\n\n [[ 98 67]]\n\n [[ 97 67]...,[ 0. 0. 0. 0. 0. 0. 0. 5. 20. ...,[ 24. 83. 66. 60. 54. 60. 19. 6. 1. ...,quercus_robur

In [51]:
import pandas as pd
import ast

# Assuming 'df' is your DataFrame

# Dictionary to store valid row data
valid_rows = {'contours': [],
              'area_hist_values': [],
              'int_hist_values': [],
              'plant': [],}

# Iterate over rows in the DataFrame
for index, row in lab.iterrows():
    try:
        contours = lab['contours'][index]
        area = ast.literal_eval(lab['area_hist_values'][index].replace('.', '.0,').replace('\n', ""))
        int = ast.literal_eval(lab['int_hist_values'][index].replace('.', '.0,').replace('\n', ""))
        plant = lab['plant'][index]
        
        valid_rows['contours'].append(contours)
        valid_rows['area_hist_values'].append(area)
        valid_rows['int_hist_values'].append(int)
        valid_rows['plant'].append(plant)

    except (SyntaxError, ValueError, TypeError):
        # Skip rows that cause evaluation errors
        continue

In [52]:
validated_lab = pd.DataFrame(valid_rows)
validated_lab

,contours,area_hist_values,int_hist_values,plant
0,[[[[144 110]]\n\n [[143 111]]\n\n [[142 111]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[20.0, 22.0, 51.0, 41.0, 46.0, 35.0, 29.0, 25....",acer_campestre
1,[[[[158 107]]\n\n [[157 108]]\n\n [[156 108]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[21.0, 31.0, 59.0, 52.0, 40.0, 41.0, 24.0, 21....",acer_campestre
2,[[[[142 86]]\n\n [[141 87]]\n\n [[140 87]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7.0, 23.0, 54.0, 34.0, 49.0, 33.0, 30.0, 24.0...",acer_campestre
3,[[[[162 85]]\n\n [[161 86]]\n\n [[160 86]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[22.0, 34.0, 54.0, 48.0, 46.0, 40.0, 24.0, 8.0...",acer_campestre
4,[[[[185 100]]\n\n [[184 101]]\n\n [[183 101]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0, 15.0, 27.0, 45.0, 40.0, 40.0, 34.0, 18.0...",acer_campestre
...,...,...,...,...
14566,[[[[109 52]]\n\n [[108 53]]\n\n [[107 53]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 8.0, 25.0,...","[23.0, 77.0, 86.0, 75.0, 69.0, 76.0, 35.0, 33....",quercus_robur
14567,[[[[115 78]]\n\n [[114 79]]\n\n [[113 79]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 11.0,...","[28.0, 68.0, 48.0, 69.0, 68.0, 54.0, 14.0, 3.0...",quercus_robur
14568,[[[[ 94 101]]\n\n [[ 93 102]]\n\n [[ 92 103]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 16.0,...","[22.0, 53.0, 69.0, 75.0, 50.0, 42.0, 17.0, 11....",quercus_robur
14569,[[[[116 79]]\n\n [[115 80]]\n\n [[114 81]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 23.0,...","[34.0, 84.0, 62.0, 59.0, 58.0, 51.0, 15.0, 5.0...",quercus_robur
14570,[[[[ 99 66]]\n\n [[ 98 67]]\n\n [[ 97 67]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 20.0,...","[24.0, 83.0, 66.0, 60.0, 54.0, 60.0, 19.0, 6.0...",quercus_robur

In [53]:
removed_nl = [d.replace('\n', "") for d in validated_lab['contours']]
removed_es = [d.replace('  ', ' ') for d in removed_nl]
added_commas = [d.replace(' ', ',') for d in removed_es]
removed_pre_commas = [d.replace('[,', '[') for d in added_commas]
removed_addi_commas = [d.replace(',,', ',') for d in removed_pre_commas]
cleaned_contours = [ast.literal_eval(d) for d in removed_addi_commas]

In [54]:
validated_lab['contours'] = cleaned_contours

In [55]:
validated_lab

,contours,area_hist_values,int_hist_values,plant
0,"[[[[144, 110]], [[143, 111]], [[142, 111]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[20.0, 22.0, 51.0, 41.0, 46.0, 35.0, 29.0, 25....",acer_campestre
1,"[[[[158, 107]], [[157, 108]], [[156, 108]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[21.0, 31.0, 59.0, 52.0, 40.0, 41.0, 24.0, 21....",acer_campestre
2,"[[[[142, 86]], [[141, 87]], [[140, 87]], [[139...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7.0, 23.0, 54.0, 34.0, 49.0, 33.0, 30.0, 24.0...",acer_campestre
3,"[[[[162, 85]], [[161, 86]], [[160, 86]], [[159...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[22.0, 34.0, 54.0, 48.0, 46.0, 40.0, 24.0, 8.0...",acer_campestre
4,"[[[[185, 100]], [[184, 101]], [[183, 101]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0, 15.0, 27.0, 45.0, 40.0, 40.0, 34.0, 18.0...",acer_campestre
...,...,...,...,...
14566,"[[[[109, 52]], [[108, 53]], [[107, 53]], Ellip...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 8.0, 25.0,...","[23.0, 77.0, 86.0, 75.0, 69.0, 76.0, 35.0, 33....",quercus_robur
14567,"[[[[115, 78]], [[114, 79]], [[113, 79]], [[112...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 11.0,...","[28.0, 68.0, 48.0, 69.0, 68.0, 54.0, 14.0, 3.0...",quercus_robur
14568,"[[[[94, 101]], [[93, 102]], [[92, 103]], [[91,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 16.0,...","[22.0, 53.0, 69.0, 75.0, 50.0, 42.0, 17.0, 11....",quercus_robur
14569,"[[[[116, 79]], [[115, 80]], [[114, 81]], [[113...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 23.0,...","[34.0, 84.0, 62.0, 59.0, 58.0, 51.0, 15.0, 5.0...",quercus_robur
14570,"[[[[99, 66]], [[98, 67]], [[97, 67]], [[96, 68...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 20.0,...","[24.0, 83.0, 66.0, 60.0, 54.0, 60.0, 19.0, 6.0...",quercus_robur

In [56]:
validated_lab.to_csv('../../csv/LAB_HOCS/validated_lab.csv')

In [142]:
import cv2
import numpy as np
import os

valid_rows = {'contours': [],
              'area_hist_values': [],
              'int_hist_values': [],
              'plant': [],}

# Create a directory to store the contour images
output_directory = "../../contour_images"
os.makedirs(output_directory, exist_ok=True)

# Iterate over the DataFrame rows
for index, row in validated_lab.iterrows():
    try:
        contour = np.array([validated_lab['contours'][index][0]])  # Replace 'contour' with the actual column name in your DataFrame
    
        plant_name = row['plant']  # Replace 'plant_name' with the actual column name in your DataFrame
        # Create a directory for the specific plant name if it doesn't exist
        plant_directory = os.path.join(output_directory, plant_name)
        os.makedirs(plant_directory, exist_ok=True)
        
        # Generate a blank image with a black background
        image = np.zeros((400, 400, 3), dtype=np.uint8)
        # Create a blank image for drawing contours
        contour_image = np.zeros_like(image)
    
        # Draw the contour on the image
        cv2.drawContours(contour_image, contour, -1, (0, 0, 255), thickness=cv2.FILLED)
    
        contours = validated_lab['contours'][index]
        area = validated_lab['area_hist_values'][index]
        int = validated_lab['int_hist_values'][index]
        plant = validated_lab['plant'][index]
        
        valid_rows['contours'].append(contours)
        valid_rows['area_hist_values'].append(area)
        valid_rows['int_hist_values'].append(int)
        valid_rows['plant'].append(plant)
    
        # Save the image in the plant name folder
        filename = os.path.join(plant_directory, f"{index}.png")  # You can adjust the filename as desired
        cv2.imwrite(filename, contour_image)
    except:
        continue

C:\Users\Jeremy\AppData\Local\Temp\ipykernel_17524\2094825128.py:17: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  contour = np.array([validated_lab['contours'][index][0]])  # Replace 'contour' with the actual column name in your DataFrame

In [143]:
validated_lab2 = pd.DataFrame(valid_rows)
validated_lab2

,contours,area_hist_values,int_hist_values,plant
0,"[[[[144, 110]], [[143, 111]], [[142, 111]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[20.0, 22.0, 51.0, 41.0, 46.0, 35.0, 29.0, 25....",acer_campestre
1,"[[[[158, 107]], [[157, 108]], [[156, 108]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[21.0, 31.0, 59.0, 52.0, 40.0, 41.0, 24.0, 21....",acer_campestre
2,"[[[[142, 86]], [[141, 87]], [[140, 87]], [[139...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7.0, 23.0, 54.0, 34.0, 49.0, 33.0, 30.0, 24.0...",acer_campestre
3,"[[[[162, 85]], [[161, 86]], [[160, 86]], [[159...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[22.0, 34.0, 54.0, 48.0, 46.0, 40.0, 24.0, 8.0...",acer_campestre
4,"[[[[185, 100]], [[184, 101]], [[183, 101]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0, 15.0, 27.0, 45.0, 40.0, 40.0, 34.0, 18.0...",acer_campestre
...,...,...,...,...
13516,"[[[[54, 74]], [[53, 75]], [[52, 75]], [[51, 76...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 18.0,...","[39.0, 64.0, 69.0, 89.0, 57.0, 52.0, 17.0, 2.0...",quercus_robur
13517,"[[[[115, 78]], [[114, 79]], [[113, 79]], [[112...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 11.0,...","[28.0, 68.0, 48.0, 69.0, 68.0, 54.0, 14.0, 3.0...",quercus_robur
13518,"[[[[94, 101]], [[93, 102]], [[92, 103]], [[91,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 16.0,...","[22.0, 53.0, 69.0, 75.0, 50.0, 42.0, 17.0, 11....",quercus_robur
13519,"[[[[116, 79]], [[115, 80]], [[114, 81]], [[113...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 23.0,...","[34.0, 84.0, 62.0, 59.0, 58.0, 51.0, 15.0, 5.0...",quercus_robur
13520,"[[[[99, 66]], [[98, 67]], [[97, 67]], [[96, 68...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 20.0,...","[24.0, 83.0, 66.0, 60.0, 54.0, 60.0, 19.0, 6.0...",quercus_robur

In [144]:
validated_lab2.to_csv('../../csv/LAB_HOCS/validated_lab2.csv')