In [145]:
import cv2
import os
import pandas as pd
import ast

In [162]:
remaining_int_1 = pd.read_csv("../../csv/LAB_HOCS/1.csv", index_col=None)
remaining_int_2 = pd.read_csv("../../csv/LAB_HOCS/2.csv", index_col=None)
remaining_int_3 = pd.read_csv("../../csv/LAB_HOCS/3.csv", index_col=None)
remaining_int_4 = pd.read_csv("../../csv/LAB_HOCS/4.csv", index_col=None)
int = pd.concat([remaining_int_1, remaining_int_2, remaining_int_3, remaining_int_4])
int = int.reset_index(drop=True)
int

                                         int_hist_values            plant
0      [ 20.  22.  51.  41.  46.  35.  29.  25.  21. ...   acer_campestre
1      [ 21.  31.  59.  52.  40.  41.  24.  21.  11. ...   acer_campestre
2      [  7.  23.  54.  34.  49.  33.  30.  24.  20. ...   acer_campestre
3      [ 22.  34.  54.  48.  46.  40.  24.   8.   4. ...   acer_campestre
4      [  3.  15.  27.  45.  40.  40.  34.  18.  26. ...   acer_campestre
...                                                  ...              ...
16778  [ 2. 13. 22.  5.  5.  3.  3.  7.  4.  4.  1.  ...  zelkova_serrata
16779  [ 9. 29. 13.  8.  9.  7.  2.  0.  1.  0.  0.  ...  zelkova_serrata
16780  [ 36.  78.  34.  11.   5.   3.   5.   1.   4. ...  zelkova_serrata
16781  [ 66.  71.  24.  12.   3.   2.   2.   5.   6. ...  zelkova_serrata
16782  [ 68.  67.  23.   8.   8.  10.   5.   3.   1. ...  zelkova_serrata

[16783 rows x 2 columns]

In [163]:
int_counts = int['plant'].value_counts()

for value, count in int_counts.items():
    print(f"{value}: {count}")

maclura_pomifera: 410
broussonettia_papyrifera: 240
acer_rubrum: 237
ulmus_rubra: 232
asimina_triloba: 199
acer_negundo: 195
diospyros_virginiana: 189
ostrya_virginiana: 183
liriodendron_tulipifera: 175
quercus_montana: 174
catalpa_bignonioides: 171
cercis_canadensis: 171
platanus_occidentalis: 165
quercus_alba: 160
acer_saccharum: 158
gleditsia_triacanthos: 152
carya_cordiformis: 148
juglans_nigra: 146
carpinus_caroliniana: 145
chionanthus_virginicus: 145
tilia_americana: 144
ulmus_americana: 135
morus_alba: 128
salix_caroliniana: 126
acer_saccharinum: 125
morus_rubra: 124
aesculus_pavi: 124
quercus_bicolor: 124
cornus_florida: 124
quercus_marilandica: 120
acer_ginnala: 120
quercus_macrocarpa: 120
magnolia_tripetala: 120
liquidambar_styraciflua: 120
koelreuteria_paniculata: 120
magnolia_acuminata: 120
magnolia_grandiflora: 120
quercus_velutina: 120
quercus_michauxii: 120
halesia_tetraptera: 120
quercus_stellata: 120
quercus_shumardii: 120
populus_deltoides: 120
quercus_coccinea: 120
quercus_phellos: 120
platanus_acerifolia: 120
malus_baccata: 120
malus_coronaria: 120
quercus_palustris: 120
malus_pumila: 120
pyrus_calleryana: 120
oxydendrum_arboreum: 120
prunus_serrulata: 120
prunus_sargentii: 120
prunus_pensylvanica: 120
paulownia_tomentosa: 120
populus_grandidentata: 120
phellodendron_amurense: 120
gymnocladus_dioicus: 120
quercus_muehlenbergii: 120
crataegus_pruinosa: 120
betula_populifolia: 120
celtis_tenuifolia: 120
castanea_dentata: 120
fraxinus_pennsylvanica: 120
ulmus_procera: 120
carya_ovata: 120
acer_pseudoplatanus: 120
cornus_kousa: 120
carpinus_betulus: 120
tilia_europaea: 120
acer_pensylvanicum: 120
betula_nigra: 120
betula_jacqemontii: 120
acer_platanoides: 120
ficus_carica: 120
aesculus_hippocastamon: 120
aesculus_glabra: 120
acer_palmatum: 120
prunus_subhirtella: 119
betula_lenta: 119
betula_alleghaniensis: 119
catalpa_speciosa: 119
amelanchier_laevis: 119
malus_floribunda: 119
cercidiphyllum_japonicum: 119
cladrastis_lutea: 119
cornus_mas: 119
crataegus_phaenopyrum: 119
prunus_yedoensis: 119
crataegus_viridis: 119
eucommia_ulmoides: 119
styrax_japonica: 119
ulmus_pumila: 119
nyssa_sylvatica: 118
chionanthus_retusus: 118
carya_tomentosa: 116
quercus_robur: 116
fagus_grandifolia: 116
quercus_imbricaria: 116
magnolia_denudata: 115
stewartia_pseudocamellia: 115
quercus_nigra: 115
amelanchier_canadensis: 114
aesculus_flava: 114
quercus_acutissima: 114
ginkgo_biloba: 112
quercus_cerris: 112
fraxinus_nigra: 112
celtis_occidentalis: 111
sassafras_albidum: 111
prunus_virginiana: 110
populus_tremuloides: 110
acer_campestre: 108
magnolia_stellata: 108
malus_hupehensis: 106
ailanthus_altissima: 104
ulmus_glabra: 102
carya_glabra: 100
zelkova_serrata: 99
tilia_tomentosa: 94
magnolia_macrophylla: 91
juglans_cinerea: 91
magnolia_virginiana: 90
tilia_cordata: 85
ilex_opaca: 83
evodia_daniellii: 80
fraxinus_americana: 80
amelanchier_arborea: 70
acer_griseum: 62
crataegus_crus-galli: 60
malus_angustifolia: 55
syringa_reticulata: 48
corylus_colurna: 48
magnolia_soulangiana: 40
quercus_rubra: 40
styrax_obassia: 40

In [146]:
compiled_lab_1 = pd.read_csv("../../csv/LAB_HOCS/LAB_HOCS_1.csv", index_col=None)
compiled_lab_2 = pd.read_csv("../../csv/LAB_HOCS/LAB_HOCS_2.csv", index_col=None)
compiled_lab_3 = pd.read_csv("../../csv/LAB_HOCS/LAB_HOCS_3.csv", index_col=None)
compiled_lab_4 = pd.read_csv("../../csv/LAB_HOCS/LAB_HOCS_4.csv", index_col=None)
lab = pd.concat([compiled_lab_1, compiled_lab_2, compiled_lab_3, compiled_lab_4])
lab = lab.reset_index(drop=True)
lab

,contours,area_hist_values,int_hist_values,plant
0,[[[[144 110]]\n\n [[143 111]]\n\n [[142 111]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 20. 22. 51. 41. 46. 35. 29. 25. 21. ...,acer_campestre
1,[[[[158 107]]\n\n [[157 108]]\n\n [[156 108]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 21. 31. 59. 52. 40. 41. 24. 21. 11. ...,acer_campestre
2,[[[[142 86]]\n\n [[141 87]]\n\n [[140 87]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 7. 23. 54. 34. 49. 33. 30. 24. 20. ...,acer_campestre
3,[[[[162 85]]\n\n [[161 86]]\n\n [[160 86]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 22. 34. 54. 48. 46. 40. 24. 8. 4. ...,acer_campestre
4,[[[[185 100]]\n\n [[184 101]]\n\n [[183 101]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 3. 15. 27. 45. 40. 40. 34. 18. 26. ...,acer_campestre
...,...,...,...,...
16778,[[[[137 124]]\n\n [[136 125]]\n\n [[135 125]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. ...,[ 2. 13. 22. 5. 5. 3. 3. 7. 4. 4. 1. ...,zelkova_serrata
16779,[[[[109 120]]\n\n [[108 121]]\n\n [[107 122]...,[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,[ 9. 29. 13. 8. 9. 7. 2. 0. 1. 0. 0. ...,zelkova_serrata
16780,[[[[118 91]]\n\n [[117 92]]\n\n [[116 92]...,[ 0. 0. 0. 0. 0. 3. 2. 2. 2. ...,[ 36. 78. 34. 11. 5. 3. 5. 1. 4. ...,zelkova_serrata
16781,[[[[136 111]]\n\n [[135 112]]\n\n [[134 112]...,[ 0. 0. 0. 0. 0. 3. 2. 2. 2. ...,[ 66. 71. 24. 12. 3. 2. 2. 5. 6. ...,zelkova_serrata
16782,[[[[ 93 116]]\n\n [[ 92 117]]\n\n [[ 91 117]...,[ 0. 0. 0. 0. 0. 0. 3. 2. 2. ...,[ 68. 67. 23. 8. 8. 10. 5. 3. 1. ...,zelkova_serrata

In [161]:
lab_counts = lab['plant'].value_counts()

for value, count in lab_counts.items():
    print(f"{value}: {count}")

maclura_pomifera: 410
broussonettia_papyrifera: 240
acer_rubrum: 237
ulmus_rubra: 232
asimina_triloba: 199
acer_negundo: 195
diospyros_virginiana: 189
ostrya_virginiana: 183
liriodendron_tulipifera: 175
quercus_montana: 174
catalpa_bignonioides: 171
cercis_canadensis: 171
platanus_occidentalis: 165
quercus_alba: 160
acer_saccharum: 158
gleditsia_triacanthos: 152
carya_cordiformis: 148
juglans_nigra: 146
carpinus_caroliniana: 145
chionanthus_virginicus: 145
tilia_americana: 144
ulmus_americana: 135
morus_alba: 128
salix_caroliniana: 126
acer_saccharinum: 125
morus_rubra: 124
aesculus_pavi: 124
quercus_bicolor: 124
cornus_florida: 124
quercus_marilandica: 120
acer_ginnala: 120
quercus_macrocarpa: 120
magnolia_tripetala: 120
liquidambar_styraciflua: 120
koelreuteria_paniculata: 120
magnolia_acuminata: 120
magnolia_grandiflora: 120
quercus_velutina: 120
quercus_michauxii: 120
halesia_tetraptera: 120
quercus_stellata: 120
quercus_shumardii: 120
populus_deltoides: 120
quercus_coccinea: 120
quercus_phellos: 120
platanus_acerifolia: 120
malus_baccata: 120
malus_coronaria: 120
quercus_palustris: 120
malus_pumila: 120
pyrus_calleryana: 120
oxydendrum_arboreum: 120
prunus_serrulata: 120
prunus_sargentii: 120
prunus_pensylvanica: 120
paulownia_tomentosa: 120
populus_grandidentata: 120
phellodendron_amurense: 120
gymnocladus_dioicus: 120
quercus_muehlenbergii: 120
crataegus_pruinosa: 120
betula_populifolia: 120
celtis_tenuifolia: 120
castanea_dentata: 120
fraxinus_pennsylvanica: 120
ulmus_procera: 120
carya_ovata: 120
acer_pseudoplatanus: 120
cornus_kousa: 120
carpinus_betulus: 120
tilia_europaea: 120
acer_pensylvanicum: 120
betula_nigra: 120
betula_jacqemontii: 120
acer_platanoides: 120
ficus_carica: 120
aesculus_hippocastamon: 120
aesculus_glabra: 120
acer_palmatum: 120
prunus_subhirtella: 119
betula_lenta: 119
betula_alleghaniensis: 119
catalpa_speciosa: 119
amelanchier_laevis: 119
malus_floribunda: 119
cercidiphyllum_japonicum: 119
cladrastis_lutea: 119
cornus_mas: 119
crataegus_phaenopyrum: 119
prunus_yedoensis: 119
crataegus_viridis: 119
eucommia_ulmoides: 119
styrax_japonica: 119
ulmus_pumila: 119
nyssa_sylvatica: 118
chionanthus_retusus: 118
carya_tomentosa: 116
quercus_robur: 116
fagus_grandifolia: 116
quercus_imbricaria: 116
magnolia_denudata: 115
stewartia_pseudocamellia: 115
quercus_nigra: 115
amelanchier_canadensis: 114
aesculus_flava: 114
quercus_acutissima: 114
ginkgo_biloba: 112
quercus_cerris: 112
fraxinus_nigra: 112
celtis_occidentalis: 111
sassafras_albidum: 111
prunus_virginiana: 110
populus_tremuloides: 110
acer_campestre: 108
magnolia_stellata: 108
malus_hupehensis: 106
ailanthus_altissima: 104
ulmus_glabra: 102
carya_glabra: 100
zelkova_serrata: 99
tilia_tomentosa: 94
magnolia_macrophylla: 91
juglans_cinerea: 91
magnolia_virginiana: 90
tilia_cordata: 85
ilex_opaca: 83
evodia_daniellii: 80
fraxinus_americana: 80
amelanchier_arborea: 70
acer_griseum: 62
crataegus_crus-galli: 60
malus_angustifolia: 55
syringa_reticulata: 48
corylus_colurna: 48
magnolia_soulangiana: 40
quercus_rubra: 40
styrax_obassia: 40

In [147]:
import pandas as pd
import ast

# Assuming 'df' is your DataFrame

# Dictionary to store valid row data
valid_rows = {'contours': [],
              'area_hist_values': [],
              'int_hist_values': [],
              'plant': [],}

# Iterate over rows in the DataFrame
for index, row in lab.iterrows():
    try:
        contours = lab['contours'][index]
        area = ast.literal_eval(lab['area_hist_values'][index].replace('.', '.0,').replace('\n', ""))
        int = ast.literal_eval(lab['int_hist_values'][index].replace('.', '.0,').replace('\n', ""))
        plant = lab['plant'][index]
        
        valid_rows['contours'].append(contours)
        valid_rows['area_hist_values'].append(area)
        valid_rows['int_hist_values'].append(int)
        valid_rows['plant'].append(plant)

    except (SyntaxError, ValueError, TypeError):
        # Skip rows that cause evaluation errors
        continue

In [148]:
validated_lab = pd.DataFrame(valid_rows)
validated_lab

,contours,area_hist_values,int_hist_values,plant
0,[[[[144 110]]\n\n [[143 111]]\n\n [[142 111]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[20.0, 22.0, 51.0, 41.0, 46.0, 35.0, 29.0, 25....",acer_campestre
1,[[[[158 107]]\n\n [[157 108]]\n\n [[156 108]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[21.0, 31.0, 59.0, 52.0, 40.0, 41.0, 24.0, 21....",acer_campestre
2,[[[[142 86]]\n\n [[141 87]]\n\n [[140 87]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7.0, 23.0, 54.0, 34.0, 49.0, 33.0, 30.0, 24.0...",acer_campestre
3,[[[[162 85]]\n\n [[161 86]]\n\n [[160 86]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[22.0, 34.0, 54.0, 48.0, 46.0, 40.0, 24.0, 8.0...",acer_campestre
4,[[[[185 100]]\n\n [[184 101]]\n\n [[183 101]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0, 15.0, 27.0, 45.0, 40.0, 40.0, 34.0, 18.0...",acer_campestre
...,...,...,...,...
16771,[[[[137 124]]\n\n [[136 125]]\n\n [[135 125]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.0, 13.0, 22.0, 5.0, 5.0, 3.0, 3.0, 7.0, 4.0...",zelkova_serrata
16772,[[[[109 120]]\n\n [[108 121]]\n\n [[107 122]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[9.0, 29.0, 13.0, 8.0, 9.0, 7.0, 2.0, 0.0, 1.0...",zelkova_serrata
16773,[[[[118 91]]\n\n [[117 92]]\n\n [[116 92]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, 2.0, ...","[36.0, 78.0, 34.0, 11.0, 5.0, 3.0, 5.0, 1.0, 4...",zelkova_serrata
16774,[[[[136 111]]\n\n [[135 112]]\n\n [[134 112]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, 2.0, ...","[66.0, 71.0, 24.0, 12.0, 3.0, 2.0, 2.0, 5.0, 6...",zelkova_serrata
16775,[[[[ 93 116]]\n\n [[ 92 117]]\n\n [[ 91 117]...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, ...","[68.0, 67.0, 23.0, 8.0, 8.0, 10.0, 5.0, 3.0, 1...",zelkova_serrata

In [149]:
removed_nl = [d.replace('\n', "") for d in validated_lab['contours']]
removed_es = [d.replace('  ', ' ') for d in removed_nl]
added_commas = [d.replace(' ', ',') for d in removed_es]
removed_pre_commas = [d.replace('[,', '[') for d in added_commas]
removed_addi_commas = [d.replace(',,', ',') for d in removed_pre_commas]
cleaned_contours = [ast.literal_eval(d) for d in removed_addi_commas]

In [150]:
validated_lab['contours'] = cleaned_contours

In [151]:
validated_lab

,contours,area_hist_values,int_hist_values,plant
0,"[[[[144, 110]], [[143, 111]], [[142, 111]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[20.0, 22.0, 51.0, 41.0, 46.0, 35.0, 29.0, 25....",acer_campestre
1,"[[[[158, 107]], [[157, 108]], [[156, 108]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[21.0, 31.0, 59.0, 52.0, 40.0, 41.0, 24.0, 21....",acer_campestre
2,"[[[[142, 86]], [[141, 87]], [[140, 87]], [[139...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7.0, 23.0, 54.0, 34.0, 49.0, 33.0, 30.0, 24.0...",acer_campestre
3,"[[[[162, 85]], [[161, 86]], [[160, 86]], [[159...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[22.0, 34.0, 54.0, 48.0, 46.0, 40.0, 24.0, 8.0...",acer_campestre
4,"[[[[185, 100]], [[184, 101]], [[183, 101]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0, 15.0, 27.0, 45.0, 40.0, 40.0, 34.0, 18.0...",acer_campestre
...,...,...,...,...
16771,"[[[[137, 124]], [[136, 125]], [[135, 125]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.0, 13.0, 22.0, 5.0, 5.0, 3.0, 3.0, 7.0, 4.0...",zelkova_serrata
16772,"[[[[109, 120]], [[108, 121]], [[107, 122]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[9.0, 29.0, 13.0, 8.0, 9.0, 7.0, 2.0, 0.0, 1.0...",zelkova_serrata
16773,"[[[[118, 91]], [[117, 92]], [[116, 92]], [[115...","[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, 2.0, ...","[36.0, 78.0, 34.0, 11.0, 5.0, 3.0, 5.0, 1.0, 4...",zelkova_serrata
16774,"[[[[136, 111]], [[135, 112]], [[134, 112]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, 2.0, ...","[66.0, 71.0, 24.0, 12.0, 3.0, 2.0, 2.0, 5.0, 6...",zelkova_serrata
16775,"[[[[93, 116]], [[92, 117]], [[91, 117]], [[90,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, ...","[68.0, 67.0, 23.0, 8.0, 8.0, 10.0, 5.0, 3.0, 1...",zelkova_serrata

In [152]:
validated_lab.to_csv('../../csv/LAB_HOCS/validated_lab.csv')

In [153]:
import cv2
import numpy as np
import os

valid_rows = {'contours': [],
              'area_hist_values': [],
              'int_hist_values': [],
              'plant': [],}

# Create a directory to store the contour images
output_directory = "../../contour_images"
os.makedirs(output_directory, exist_ok=True)

# Iterate over the DataFrame rows
for index, row in validated_lab.iterrows():
    try:
        contour = np.array([validated_lab['contours'][index][0]])  # Replace 'contour' with the actual column name in your DataFrame
    
        plant_name = row['plant']  # Replace 'plant_name' with the actual column name in your DataFrame
        # Create a directory for the specific plant name if it doesn't exist
        plant_directory = os.path.join(output_directory, plant_name)
        os.makedirs(plant_directory, exist_ok=True)
        
        # Generate a blank image with a black background
        image = np.zeros((400, 400, 3), dtype=np.uint8)
        # Create a blank image for drawing contours
        contour_image = np.zeros_like(image)
    
        # Draw the contour on the image
        cv2.drawContours(contour_image, contour, -1, (0, 0, 255), thickness=cv2.FILLED)
    
        contours = validated_lab['contours'][index]
        area = validated_lab['area_hist_values'][index]
        int = validated_lab['int_hist_values'][index]
        plant = validated_lab['plant'][index]
        
        valid_rows['contours'].append(contours)
        valid_rows['area_hist_values'].append(area)
        valid_rows['int_hist_values'].append(int)
        valid_rows['plant'].append(plant)
    
        # Save the image in the plant name folder
        filename = os.path.join(plant_directory, f"{index}.png")  # You can adjust the filename as desired
        cv2.imwrite(filename, contour_image)
    except:
        continue

C:\Users\Jeremy\AppData\Local\Temp\ipykernel_17524\2094825128.py:17: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  contour = np.array([validated_lab['contours'][index][0]])  # Replace 'contour' with the actual column name in your DataFrame

In [154]:
validated_lab2 = pd.DataFrame(valid_rows)
validated_lab2

,contours,area_hist_values,int_hist_values,plant
0,"[[[[144, 110]], [[143, 111]], [[142, 111]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[20.0, 22.0, 51.0, 41.0, 46.0, 35.0, 29.0, 25....",acer_campestre
1,"[[[[158, 107]], [[157, 108]], [[156, 108]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[21.0, 31.0, 59.0, 52.0, 40.0, 41.0, 24.0, 21....",acer_campestre
2,"[[[[142, 86]], [[141, 87]], [[140, 87]], [[139...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7.0, 23.0, 54.0, 34.0, 49.0, 33.0, 30.0, 24.0...",acer_campestre
3,"[[[[162, 85]], [[161, 86]], [[160, 86]], [[159...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[22.0, 34.0, 54.0, 48.0, 46.0, 40.0, 24.0, 8.0...",acer_campestre
4,"[[[[185, 100]], [[184, 101]], [[183, 101]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.0, 15.0, 27.0, 45.0, 40.0, 40.0, 34.0, 18.0...",acer_campestre
...,...,...,...,...
15417,"[[[[137, 124]], [[136, 125]], [[135, 125]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.0, 13.0, 22.0, 5.0, 5.0, 3.0, 3.0, 7.0, 4.0...",zelkova_serrata
15418,"[[[[109, 120]], [[108, 121]], [[107, 122]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[9.0, 29.0, 13.0, 8.0, 9.0, 7.0, 2.0, 0.0, 1.0...",zelkova_serrata
15419,"[[[[118, 91]], [[117, 92]], [[116, 92]], [[115...","[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, 2.0, ...","[36.0, 78.0, 34.0, 11.0, 5.0, 3.0, 5.0, 1.0, 4...",zelkova_serrata
15420,"[[[[136, 111]], [[135, 112]], [[134, 112]], [[...","[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, 2.0, ...","[66.0, 71.0, 24.0, 12.0, 3.0, 2.0, 2.0, 5.0, 6...",zelkova_serrata
15421,"[[[[93, 116]], [[92, 117]], [[91, 117]], [[90,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 2.0, ...","[68.0, 67.0, 23.0, 8.0, 8.0, 10.0, 5.0, 3.0, 1...",zelkova_serrata

In [155]:
validated_lab2.to_csv('../../csv/LAB_HOCS/validated_lab2.csv')